//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenancy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contract
    {
        public int ContractCode { get; set; }
        public int Lessee_ID { get; set; }
        public int Lessor_ID { get; set; }
        public int СommercialPremises_Code { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime RentalStartDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime RentalEndDate { get; set; }
        public string FileNameContract { get; set; }
        public byte[] FileDataContract { get; set; }
        public string FileNameLessee { get; set; }
        public string FileDataLessee { get; set; }
    
        public virtual Lessee Lessee { get; set; }
        public virtual Lessor Lessor { get; set; }
        public virtual Premises Premises { get; set; }
    }
}
