//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenancy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Lessee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lessee()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int Lessee_ID { get; set; }
        [Required]
        public string Organization { get; set; }
        public string Trademarks { get; set; }
        [Required]
        public string BrandType { get; set; }
        [Required]
        public string TradingProfile { get; set; }
        public string ProductProfile { get; set; }
        public string FileNameSlide { get; set; }
        public byte[] FIleData { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        public string Name { get; set; }
        public string SecondName { get; set; }
        //[Required]
        public int СommercialPremises_Code { get; set; }
        [Required]
        public string Email { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string ApplicationStatus { get; set; }
        public string ApplicationDescription { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> RentalStartDate { get; set; }
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> RentalEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Register Register { get; set; }
    }
}
