//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenancy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TenancyEntities : DbContext
    {
        public TenancyEntities()
            : base("name=TenancyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Lessee> Lessee { get; set; }
        public virtual DbSet<Lessor> Lessor { get; set; }
        public virtual DbSet<Premises> Premises { get; set; }
        public virtual DbSet<Register> Register { get; set; }
    }
}
