//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenancy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Premises()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int СommercialPremises_Code { get; set; }
        public int Floor { get; set; }
        public double Square { get; set; }
        public Nullable<double> UtilityRoom { get; set; }
        public Nullable<int> Windows { get; set; }
        public string Electricity { get; set; }
        public string WaterSupply { get; set; }
        public string Conditioner { get; set; }
        public string Details { get; set; }
        public decimal CostPerSM { get; set; }
        public string ApplicationStatus { get; set; }
        public int Lessor_ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Lessee_ID { get; set; }
        public int PremisesCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Lessor Lessor { get; set; }
    }
}
